### ISSUE TITLE
GPT-4 vision not processing images

### ISSUE THREAD

**Issue by shanelle627** [lightrail-ai/lightrail#62]
OSX 

<img width="599" alt="image" src="https://github.com/lightrail-ai/lightrail/assets/118563604/b35d607b-b8cb-4c86-bb1f-48f3d7cb1e06">

Logs: 
[2023-11-10 15:04:16.563] [error] Error: Something went wrong processing one of your images.
    at APIError.generate (/Applications/lightrail.app/Contents/Resources/app/node_modules/openai/error.js:67:14)
    at OpenAI.makeStatusError (/Applications/lightrail.app/Contents/Resources/app/node_modules/openai/core.js:312:29)
    at OpenAI.makeRequest (/Applications/lightrail.app/Contents/Resources/app/node_modules/openai/core.js:352:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Applications/lightrail.app/Contents/Resources/app/node_modules/langchain/dist/chat_models/openai.cjs:517:29
    at async RetryOperation._fn (/Applications/lightrail.app/Contents/Resources/app/node_modules/p-retry/index.js:50:12)
[2023-11-10 15:04:16.579] [error] Error executing action:  TRPCClientError: Something went wrong processing one of your images.
    at y.from (file:///Applications/lightrail.app/Contents/Resources/app/out/renderer/assets/index-db7be566.js:18836:10)
    at Object.next (file:///Applications/lightrail.app/Contents/Resources/app/out/renderer/assets/index-db7be566.js:19263:23)
    at V.M (file:///Applications/lightrail.app/Contents/Resources/app/out/renderer/assets/index-db7be566.js:19245:23)
    at Function.<anonymous> (file:///Applications/lightrail.app/Contents/Resources/app/out/renderer/assets/index-db7be566.js:19223:21)

**Comment by vishnumenon** [comment]
Seems like this was due to upstream downtime w/ the openai service

https://community.openai.com/t/gpt-4-vision-api-internal-server-error-something-wrong-processing-one-of-your-images/493958/2
